[package]
name = "algorithms_in_rust"
version = "0.1.0"
edition = "2018"
authors = ["Victor A. S. Nascimento <victor.as.nascimento@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
